services:
  studentaffairssystem.adminwebapp:
    image: adminwebapp
    build:
      context: .
      dockerfile: AdminWebApp/Dockerfile

  studentaffairssystem.webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
